# Generated by Django 4.0.4 on 2022-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '8. Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '9. Order items'},
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='total_amot',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='total_amt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
